name: employers_widget_backend
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  args: ^2.0.0
  neat_periodic_task: ^2.0.0
  shelf: ^1.1.0
  shelf_cors_headers: ^0.1.4
  shelf_router: ^1.0.0
  time: ^2.1.3


dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.15.0
